version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: servitask-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: servitask
      MYSQL_USER: servitask_user
      MYSQL_PASSWORD: servitask_password
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - servitask-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: servitask-backend
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/servitask?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=servitask_user
      - SPRING_DATASOURCE_PASSWORD=servitask_password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQL8Dialect
    ports:
      - "8083:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - servitask-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: servitask-frontend
    environment:
      - VITE_API_URL=http://localhost:8083
    ports:
      - "3310:3310"
    depends_on:
      - backend
    networks:
      - servitask-network
    restart: unless-stopped

networks:
  servitask-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local 